import ExtensionPage from 'flarum/admin/components/ExtensionPage';
import type Mithril from 'mithril';
import type { Badge, BadgeCategory } from '../../common';
interface RecalculationProgress {
    id: number;
    status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
    totalUsers: number;
    processedUsers: number;
    totalBadges: number;
    awarded: number;
    revoked: number;
    skipped: number;
    percentage: number;
    totalChunks: number;
    processedChunks: number;
    chunkPercentage: number;
    chunkSize: number;
    startedAt: string | null;
    completedAt: string | null;
    errorMessage: string | null;
}
interface RecalculationJob {
    id: number;
    status: string;
    totalUsers: number;
    processedUsers: number;
    totalBadges: number;
    awarded: number;
    revoked: number;
    skipped: number;
    percentage: number;
    totalChunks: number;
    processedChunks: number;
    chunkSize: number;
    startedAt: string | null;
    completedAt: string | null;
    errorMessage: string | null;
    createdAt: string;
}
export default class BadgesPage extends ExtensionPage {
    loading: boolean;
    recalculating: boolean;
    badges: Badge[];
    categories: BadgeCategory[];
    activeTab: 'badges' | 'categories' | 'recalculation' | 'settings';
    recalculationProgress: RecalculationProgress | null;
    pollInterval: ReturnType<typeof setInterval> | null;
    selectedBadgeId: string;
    chunkSize: number;
    noRevoke: boolean;
    reapplyActions: boolean;
    startingRecalculation: boolean;
    autoRefresh: boolean;
    jobs: RecalculationJob[];
    loadingJobs: boolean;
    jobsDisplayCount: number;
    syncingCounts: boolean;
    savingSettings: boolean;
    installingDefaults: boolean;
    destroyed: boolean;
    oninit(vnode: Mithril.Vnode): void;
    onremove(vnode: Mithril.VnodeDOM): void;
    startPolling(): void;
    stopPolling(): void;
    checkRecalculationStatus(): Promise<void>;
    loadData(): Promise<void>;
    loadJobs(): Promise<void>;
    content(): JSX.Element;
    recalculationTab(): Mithril.Children;
    settingsTab(): Mithril.Children;
    integrationsSection(): Mithril.Children;
    saveSettings(): Promise<void>;
    saveSettingsToDatabase(): Promise<void>;
    recalculationProgressBar(): Mithril.Children;
    jobsList(): Mithril.Children;
    jobItem(job: RecalculationJob): Mithril.Children;
    dismissProgress(): void;
    cancelRecalculation(): Promise<void>;
    cancelJob(jobId: number): Promise<void>;
    startRecalculation(): Promise<void>;
    syncBadgeCounts(): Promise<void>;
    badgesList(): Mithril.Children;
    badgeItem(badge: Badge, index: number, categoryBadges: Badge[]): Mithril.Children;
    categoriesList(): Mithril.Children;
    categoryItem(category: BadgeCategory, index: number): Mithril.Children;
    openBadgeModal(badge?: Badge): void;
    openCategoryModal(category?: BadgeCategory): void;
    openAssignModal(badge: Badge): void;
    deleteBadge(badge: Badge): Promise<void>;
    deleteCategory(category: BadgeCategory): Promise<void>;
    moveCategory(category: BadgeCategory, direction: 'up' | 'down'): Promise<void>;
    moveBadge(badge: Badge, direction: 'up' | 'down'): Promise<void>;
    installDefaults(): Promise<void>;
}
export {};
